# Generated by Django 4.2.7 on 2026-04-12 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_supplierpayment_purchase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-purchase_date'], 'verbose_name': 'Purchase', 'verbose_name_plural': 'Purchases'},
        ),
        migrations.AlterModelOptions(
            name='supplierpayment',
            options={'ordering': ['-paid_at'], 'verbose_name': 'Supplier Payment', 'verbose_name_plural': 'Supplier Payments'},
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='date',
            new_name='purchase_date',
        ),
        migrations.RenameField(
            model_name='supplierpayment',
            old_name='note',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='supplierpayment',
            old_name='date',
            new_name='paid_at',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='price_per_unit',
            field=models.IntegerField(verbose_name='Birlik narxi'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='quantity',
            field=models.IntegerField(verbose_name='Miqdori'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='finance.supplier', verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total_cost',
            field=models.IntegerField(verbose_name='Jami narx'),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('bank', "Pul ko'chirish"), ('cash', 'Naqd'), ('click', 'Click')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.supplier', verbose_name='Firma'),
        ),
    ]
