# Generated by Django 4.2.7 on 2026-04-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Mavjud miqdor (kg)'),
        ),
    ]
