# Generated by Django 4.2.7 on 2026-04-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='promo_buy',
            field=models.IntegerField(blank=True, null=True, verbose_name='Aksiya: nechta sotib olsa'),
        ),
        migrations.AddField(
            model_name='product',
            name='promo_free',
            field=models.IntegerField(blank=True, null=True, verbose_name='Aksiya: nechta bepul'),
        ),
    ]
