# Generated by Django 4.2.7 on 2026-04-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_product_promo_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='initial_debt',
            field=models.IntegerField(default=0, verbose_name="Boshlang'ich qarz"),
        ),
    ]
