# Generated by Django 4.2.7 on 2026-04-27 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_supplier_initial_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='barter_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barter_purchases', to='finance.product', verbose_name='Barter mahsuloti'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='barter_quantity',
            field=models.IntegerField(default=0, verbose_name='Barter miqdori'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_type',
            field=models.CharField(choices=[('cash', 'Naqd'), ('credit', 'Qarz'), ('barter', 'Barter (Ayirboshlash)')], default='cash', max_length=20, verbose_name='Xarid turi'),
        ),
    ]
