# Generated by Django 4.2.7 on 2026-04-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_purchase_barter_product_purchase_barter_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='price_per_unit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Birlik narxi'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total_cost',
            field=models.IntegerField(default=0, verbose_name='Jami narx'),
        ),
    ]
