# Generated by Django 4.2.7 on 2026-05-02 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_alter_purchase_price_per_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpayment',
            name='barter_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barter_supplier_payments', to='finance.product', verbose_name='Barter mahsuloti'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='barter_quantity',
            field=models.IntegerField(default=0, verbose_name='Barter miqdori'),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('bank', "Pul ko'chirish"), ('cash', 'Naqd'), ('click', 'Click'), ('barter', 'Barter (Mahsulot)')], max_length=20, null=True),
        ),
    ]
