# Generated by Django 4.2.7 on 2026-05-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_usd_fields_and_customer_barter'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='batch_id',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
    ]
